name: 'Setup Sentinel'
description: 'Setup Sentinel and add it to the PATH'
author: 'volcano-coffee-company'
branding:
  icon: 'clipboard'
  color: 'gray-dark'
inputs: 
  version:
    description: 'The Sentinel version to download (if necessary) and use. Example: ~> 0.13'
    default: '0.13'
runs:
  using: 'node12'
  main: 'lib/setup-sentinel.js'
